### ISSUE TITLE
bug: Shadows are not drawn on characters

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#100]
Not sure if this ever worked (correctly)? I've definitely noticed situations where shadows are drawn as simple rectangles. However, as of the latest builds they don't seem to be drawn at all. Comparisons from the start of the game in DOS and the port:

DOS:
![](https://i.ibb.co/YWQdwv4/dos4gw-209.png)

Port:
![](https://i.ibb.co/gz4fkKH/Desktop-Screenshot-2023-12-11-20-05-15-39.png)

Edit:
On the oldest Github actions build available (1334) shadows are not working. However, shadows DO work correctly on the ancient 797 release. I also notice that the lighting is harsher and with more banding than the DOS version and the 797 release now.
Oldest Github build I have is 847 and that does not work either. So it's obviously a change from 797 - 847.

**Comment by mefistotelis** [comment]
I will have to star making releases every 20 commits or so. Otherwise the issues with bisection will make such bugs much harder.

**Comment by mefistotelis** [comment]
There seem to be a separate issue with no shadows when mission is loaded directly (via -m).
Looks like the shadows are then switched off, and cannot be turned on again.

**Comment by mefistotelis** [comment]
Fixed with:
swars: Fixed incorrectly remade copy_from_screen_ani() 

Though I'm not sure what about the enabling of shadows when using `-m`.
May be material for another issue.

**Comment by Moburma** [comment]
It turns out the -m no shadows issue is actually an original game bug, I tested it just now in DOS. I never realised that was the case before. Probably some kind of debug thing to keep things simple when testing. 
This issue can be closed as it's a regression from the original, I guess it's debatable whether it's worth fixing the -m shadows issue or not, you're not really meant to play the game that way.

**Comment by Moburma** [comment]
Fixed

**Comment by mefistotelis** [comment]
> I guess it's debatable whether it's worth fixing the -m shadows issue or not, you're not really meant to play the game that way.

The game often duplicates code which does the same thing, only with minor differences. Original sources were just very messy.

Have you noticed you can change volume faster by holding shift while clicking at inc/dec triangles? Well, in some slider at least. Others do that with ctrl. And a few don't have this function at all.
Every slider in the game has its own, unique implementation, for some reason.

Same goes with loading the level - there's the "menu way" and the "cmdline way". There was also a "restart way" and "two consecutive levels after each other way", but those I already downgraded to one function.

This not only makes any changes harder, but also debug and reverse-engineering. I am typically able to recognized inlined functions when RE-ing, and quickly use the original if it's already remade. But here, functions which do the same thing are in most cases still unique.

I am going to unify such places. So yeah, an "issue" can be created for that.
