### ISSUE TITLE
EuroCorp Mission 06: Long health bar on flying police vehicle

### ISSUE THREAD

**Issue by geist22** [swfans/swars#104]
Original game bug.

There's a flying police vehicle near your starting position that soon explodes while you hear the LR Rifle shooting sound. I assume this is a scripted event to simulate it being shot down by the Unguided. When this happens, you see its health bar extended to the right.

![eurocorp06_rome](https://github.com/swfans/swars/assets/107389189/99706f34-f96b-44ac-8a9e-3ec9931871ab)

**Comment by Moburma** [comment]
The car is deliberately set to an armour value of 0 (it's ThingOffset 331 in the level file), so starts with literally no health so it dies from one shot. I guess it's some kind of overflow error where the LR rifle shot causes the health to go so far negative it wraps back around to maximum.

**Comment by mefistotelis** [comment]
> the LR rifle shot causes the health to go so far negative it wraps back around to maximum.

Either that, or signed value is treated as unsigned.

**Comment by geist22** [comment]
Heh, it really does, you can intercept it with the Minigun before the crash if you're quick enough, and shooting it with the LR will cause this long bar, too.

**Comment by mefistotelis** [comment]
Looks like I fixed it with my recent rendering functions rewrite.

**Comment by geist22** [comment]
Yes, seems fixed.
