### ISSUE TITLE
Crash when trying to play the same mission two consecutive times

### ISSUE THREAD

**Issue by geist22** [swfans/swars#105]
Easiest way to reproduce:

1. Enter an optional mission (EuroCorp 3 or 10)
2. Abort mission
3. Try to play the same mission again

Game crashes without error message. If you play another mission in between, it works. Also happens when starting new games or loading savegames.

**Comment by geist22** [comment]
[0.3.5.1608](https://github.com/swfans/swars/releases/tag/0.3.5.1608) still works
[0.3.6.1624](https://github.com/swfans/swars/releases/tag/0.3.6.1624) doesn't work anymore

**Comment by mefistotelis** [comment]
Introduced by:
[Finally unified use of init_game()](https://github.com/swfans/swars/commit/92d433e12bec5c64716e1bd95660f117c8de120d)
Fixed by:
[swars: Fix loading the same mission 2nd time](https://github.com/swfans/swars/commit/1926852712b29d6443894c082b02671c4bf03d87)

**Comment by geist22** [comment]
Confirmed as working.
