### ISSUE TITLE
More debriefing text alignment issues

### ISSUE THREAD

**Issue by geist22** [swfans/swars#106]
As you can see in the screenshot below, if the completed research doesn't fit into a single line, it starts overlapping with the lost scientists.

![debriefing](https://github.com/swfans/swars/assets/107389189/995fa5de-017c-430c-8a45-c3d1323a0067)

The original game shows only one completed research while omitting the rest, in this case you'd only see "High Explosive" with no mention of the Legs Lv2.

Unfortunately it doesn't look like there's enough space to just move down the scientists one row, as this one here also takes up two lines. You could move scientists down one row if it's only one line, and otherwise move the whole block from "Income" up one row. Or perhaps move the column a bit to the left, so it fits on one line.

**Comment by mefistotelis** [comment]
Ideas:

1. Move the 2nd column left. Check how much space we can get by verifying all languages. Possibly shorten the text if a line or two for specific language is noticeably longer.
Pros: easy to do, provides justification to also reorganize the lower box (would be nice to add more stats there)
Cons: the column in upper and lower box will no longer align, you get only space for 1 word, not a line

2. Use "compact mode" if research completed and scientists death is active at the same time. In this mode, all empty lines are half the height.
Pros: gives a whole line (half of line at top, and half before "income")
Cons: the box will look more stuffed, the code needs to be reorganized to "know" up front how many lines will be required

3. Change font of some text to a smaller one. There is a smaller font used in the right column. Use that for scientists death reason and weapon+mod names.
Pros: can fit considerably more with the smaller font
Cons: A different font for for some values will look a bit inconsistent

We can use any combination of the above

**Comment by geist22** [comment]
Names of mods could easily be abbreviated, e.g. "Legs Level 2" -> "Legs 2".

Names of weapons are harder. High Explosive is among the longer names, only Electron Mace, Nuclear Grenade, Long Range Rifle and Persuadertron II take up more space. Some just don't look right if shortened, but only abbreviating mods isn't enough to fit it on one line together with one of the weapons with a longer name.

I've also noticed just now that the text on the left side of the boxes doesn't align. In the upper box, the text starts one space further to the right compared to the lower box.

**Comment by mefistotelis** [comment]
Abbreviating weapon names would require introducing the abbreviated list to translations, and supporting in all languages. That would also be confusing.

For mods - the debriefing screen actually does not use standard names of these, instead gluing a name together with separate translated words. If I remember correctly, the fully translated mod names are shorter - will have to check that.

So we could add to the possibilities:

4. Use shorter names for mods.

For weapons - I don't think it's justified.

**Comment by mefistotelis** [comment]
I made the game reserve correct amount of lines upfront. So 1-4 are not implemented as of now, just no overlap.

![synII057](https://github.com/swfans/swars/assets/11463396/5dcd2b91-28c4-44f7-985e-0c235deb01c6)
![synII058](https://github.com/swfans/swars/assets/11463396/9761573e-5650-4608-aba3-ae605201270b)

**Comment by mefistotelis** [comment]
The (1) cannot be done - in some languages the text barely fits. Example:
![synII060](https://github.com/swfans/swars/assets/11463396/e5bb5159-1287-4275-bc62-ef9ef390d4af)

**Comment by mefistotelis** [comment]
Implemented (2) - so it's done. Now you'd have to be very creative to overflow the list. I'm not sure it's possible at all, as the buffer used for storing names has limited size. The game can figure out how to get up to 5 lines of text for the research list.

**Comment by geist22** [comment]
So (3) has priority over (2)?

![debrief](https://github.com/swfans/swars/assets/107389189/7320481b-262b-4a43-82b4-291a68c74160)

I think the different font looks worse than the other solutions, so it might make sense to use it as last resort only when research + scientists takes more than 4 lines total, though I haven't seen (2) in action because the game seems to prefers (3) over it.

How would it look with the empty lines at the very top and bottom of the box halved instead?

**Comment by mefistotelis** [comment]
> So (3) has priority over (2)?

It's more complicated.
For "Scientists dead" multi-line is not supported at all, only font decrease.

The game first makes a decision about amount of lines reserved to the extra options (up to 3 lines for research, up to 1 for dead scientists). Then during the drawing, it compares the string size to already set amount of lines, and based on that chooses font size.

**Comment by geist22** [comment]
Wouldn't going with 2+2 lines instead of 3+1 for research/scientists make it prefer (2) over (3) then, and only fall back to the smaller font when research is more than 2 lines? That might give the screen a more consistent look.

Getting more than 2 lines of research seems pretty hard during regular gameplay.

**Comment by mefistotelis** [comment]
Maybe I'm biased against the "reason" there. It is unimportant, really - provides no gameplay information, only adds a rudimentary story to the supposed death. When I saw it in game during 2nd playthrough (on 1st I wasn't even reading these), it only confused me. The short message didn't made much sense to me, and overshadowed the "1" before it, which is the only part that does convey important information. I wasn't even sure if it's a number or a letter "i".

Allocating 2 lines for the "reason" is fully doable if amount of lines for "research" is <= 2. We could, I'm just not fully convinced if we should.

**Comment by geist22** [comment]
I'm not arguing that the "reason" is important - it's just flavor text.

I just think that mixing two different fonts together in the main box probably looks worse than the other solutions (I haven't actually seen (2) in action so I don't know for sure), so it might make sense to use it only when absolutely necessary.

Perhaps you could post a screenshot without smaller font and 2+2 lines for comparison, as I can't get it to work this way?

**Comment by mefistotelis** [comment]
Here it is:

![synII066](https://github.com/swfans/swars/assets/11463396/ea6197db-e5f6-4de1-a026-1adfa9335b78)

**Comment by geist22** [comment]
Thanks. Wouldn't you call this a more consistent look than https://github.com/swfans/swars/issues/106#issuecomment-1867837095?

Scientists dead should hopefully not be too common, and unless you're playing in a different language with longer names, you'd have to try pretty hard to get more than two lines of research.

I hope I'm not coming off as annoying, especially since you're doing all the work by yourself. I'm somewhat of a perfectionist, so I place great value even in all the little things like these.

**Comment by mefistotelis** [comment]
Generally such case wouldn't be worth working on. Looking at the screenshots long enough, I do lean towards same font, but barely.

Regardless, I did implemented this:
[swars: Allow scientist death reason to take 2 lines](https://github.com/swfans/swars/commit/4a2e97ecc5b688adb0b3410eda8c11387605ba2c)

**Comment by geist22** [comment]
Appreciate it, I do think it looks better this way, as 2 or more lines of research shouldn't happen all that often.
