### ISSUE TITLE
Tangent: https://syndicate.lubiki.pl/ fansite down?

### ISSUE THREAD

**Issue by DaleCulpin** [swfans/swars#107]
Apologies for putting this here like this as it isn't a bug or feature request.

@mefistotelis , I belive this is your creation?

https://syndicate.lubiki.pl/

**Wayback machine:**
https://web.archive.org/web/20220909115033/http://syndicate.lubiki.pl/swars/html/swars_main.php
https://web.archive.org/web/20220909115052/http://syndicate.lubiki.pl/siteinfo/contact.php

It's been around for ages and I used to visit it every now and then when I thought about Syndicate Wars. Always found the Book of Cataclysm quote collection entertaining:

https://web.archive.org/web/20220908164714/http://syndicate.lubiki.pl/swars/html/swars_book_cataclysm.php

Since finally locating my old copy of Syndicate Wars and installating this **swars** port (which I'm loving!), I've been using the website a fair bit. It's been down recently though.

Just wondering what's up. Will the site be back up at any point or has it been finally shut down?  Be sad to lose it.

Anyway, end of tangent, and thanky you very much for one of my favourite little corners of the internet.

Cheers.

**Comment by mefistotelis** [comment]
Hi,

> @mefistotelis , I belive this is your creation?
> http**s**://syndicate.lubiki.pl/

looks like you didn't noticed a subtle difference in the address.

```
https://web.archive.org/web/20220909115052/http://syndicate.lubiki.pl/siteinfo/contact.php
                                               ^
                                               here
```

I'm pretty sure the site is working. I can even hear the fan of the 20 years old laptop in the hall of my flat, on which the site is hosted.
I guess it needs some dusting..

**Comment by Moburma** [comment]
It's because most mobile browsers now try and force https. As explained above the site doesn't use it, so for me I can't go on it at all on Brave on my phone as it always forces me to use https which doesn't exist. On Firefox on my computer it works fine.

**Comment by mefistotelis** [comment]
Ok, fine.

```
$ sudo a2ensite syndicate.lubiki.pl-ssl
Enabling site syndicate.lubiki.pl-ssl.
To activate the new configuration, you need to run:
  systemctl reload apache2
$ sudo systemctl reload apache2
$

```

**Comment by DaleCulpin** [comment]
Ah well, I feel very silly now!

I've been using the same bookmark forever, not sure why it messed up HTTP/HTTPS prefix when I've been visiting recently.

Thanks for your response anyway!
