### ISSUE TITLE
More wrongly marked mission objectives

### ISSUE THREAD

**Issue by geist22** [swfans/swars#108]
Found some more wrongly marked mission objectives, using the latest build with the respective misXXX.ini files.

1. Space Station, the self-destruct deactivation
2. Moon (both sides), the mission counts as finished from the start but cannot be completed

**Comment by Moburma** [comment]
On the first one, do you mean the "Get shuttle nav computer" objective? That seems to be wrong now, but in an odd way. It's now pointing to the object needed for the second item objective "get shuttle life support module". I need to play through it without cheating, but the self destruct one was always deliberately vague and has no visible objectives. I think this possibly the newer item finding code getting confused.

Moon is just screwed, but I can't see why. The only objectives are kill group 1 - the nine, and that is as basic as objectives get in this game, unless they have somehow changed group? I will have a poke about. Probably worth bisecting the moon one.

**Comment by geist22** [comment]
> On the first one, do you mean the "Get shuttle nav computer" objective? That seems to be wrong now, but in an odd way. It's now pointing to the object needed for the second item objective "get shuttle life support module". 

I didn't pay that close attention to the objectives, I just played through the mission like I always do, as I generally know what you need to do, and noticed I got stuck after killing the last Zealot on the map and the "disable self-destruct" objective was outside the playable map on the radar.

I'll have to play through it again in both port and original and compare.

**Comment by mefistotelis** [comment]
[0.3.5.1555](https://github.com/swfans/swars/releases/tag/0.3.5.1555) - works
[0.3.5.1582](https://github.com/swfans/swars/releases/tag/0.3.5.1582) - stopped working

**Comment by mefistotelis** [comment]
Should be fixed.

**Comment by Moburma** [comment]
Yes, confirmed fixed here, both bugs (I didn't play through the whole shuttle level, but the first objective is now correct again).

**Comment by geist22** [comment]
Space Station objectives are now in the correct order, and you can complete the level, but the radar already points to the zealot with the life support module when you're on the self destuct. Self destruct objective should not have a map marker. You only get pointed there by the moving camera after you place agents to deactivate the traps.

Moon works.

Also, the game crashes after the cutscene, but I've opened a new issue for this one: https://github.com/swfans/swars/issues/110

**Comment by mefistotelis** [comment]
Fixed - the same flag was used for two different meanings in the objectives.

**Comment by geist22** [comment]
Yes, now it's working.
