### ISSUE TITLE
Skipping cutscenes with Enter skips debriefing if new mission is available

### ISSUE THREAD

**Issue by geist22** [swfans/swars#113]
Original game issue.

The "Mission Complete" cutscenes can be skipped with a few keys - Escape, Space and the main Enter (numpad Enter doesn't work) from what I've found so far.

Escape and Space will bring you back to the menu and show the debriefing screen. But if you hit Enter during the cutscene, it will skip the debriefing screen and immediately open the next mission, if you have mail for a newly received mission.

In the menus, pressing Enter will open new mail. Could it be that using Enter to skip a cutscene triggers multiple times or queues actions?

**Comment by mefistotelis** [comment]
In bullfrog library, you need to "clear" key presses - to avoid losing short-pressed key, the library kind of "locks" the key after the press, and the app based on it is supposed to clear the key after its use.

I did noticed that this is done after playing some videos, but not all.

**Comment by mefistotelis** [comment]
Was it fixed with this?:
https://github.com/swfans/swars/commit/0c21512c4a5af79882abde11e09041994f9fa2ee

**Comment by geist22** [comment]
Yes, works for me.
