### ISSUE TITLE
Can't buy mods for all agents if they're unmodded

### ISSUE THREAD

**Issue by geist22** [swfans/swars#121]
Steps to reproduce:

1. Start a new game
2. Go to cryo chamber and enable "all agents"

The Body Lv1 disappears from the list and you'll have an empty list with nothing to buy. Before it works, you need to buy a Body Lv1 for each agents separately.

**Comment by mefistotelis** [comment]
Should be fixed with:
[swars: Fix allowing mods purchase if agents have body mod](https://github.com/swfans/swars/commit/68875d1b4e69c0255dfe17767b393532ab5b0acc)

**Comment by geist22** [comment]
Confirmed for working.
