### ISSUE TITLE
Briefcase popup bugged when standing on top of item

### ISSUE THREAD

**Issue by geist22** [swfans/swars#126]
Items you can pick up during missions have two kind of popups, one on mouseover, and one when your agent stands on top of it.

The popup for the briefcases (both credits and quest items) has a bugged appearance where the icon is moved a bit upwards and to the left compared to the border around it, but only when standing on the item. The mouseover popup displays correctly.

![01](https://github.com/swfans/swars/assets/107389189/4880cc83-8a88-4d5e-b2d2-d643c51ee77d)

So far I haven't found any other items that cause a bugged popup.

**Comment by geist22** [comment]
[0.3.3.797](https://github.com/swfans/swars/releases/tag/0.3.3.797) latest release without bug
[0.3.3.825](https://github.com/swfans/swars/releases/tag/0.3.3.825) first release with bug

**Comment by geist22** [comment]
I have no idea what I'm doing, but I'm trying something anyway.

It looks like in `game.c`, line 3128 is the position for weapons and 3130 for non-weapons like our briefcase here, while 3159 and 3161 are the same but for mouseover. They don't have the same value for some reason, so I've changed the former to match the latter in https://github.com/swfans/swars/pull/127

**Comment by mefistotelis** [comment]
Yeah, that looks like a correct change.
