### ISSUE TITLE
bug: Objects don't align with terrain

### ISSUE THREAD

**Issue by geist22** [swfans/swars#152]
Objects such as buildings and people are shifted compared to the terrain.

Old:
![old](https://github.com/swfans/swars/assets/107389189/78560772-9ca3-4171-b55c-619eaa968610)

New:
![new](https://github.com/swfans/swars/assets/107389189/6342c907-6285-4ea1-a15f-55f961b6350f)

Probably introduced in https://github.com/swfans/swars/commit/f519f4b3e336416b6eed4d3700e6751fcb0177c2

**Comment by mefistotelis** [comment]
Oh wow. Yeah, looks like changing render area by one shifts the ground back and forth. So render area should either be odd or even, not sure which one.

**Comment by mefistotelis** [comment]
Can you make a test? If you add this one line:
```
diff --git a/src/enginzoom.c b/src/enginzoom.c
index bd40d03..1b39723 100644
--- a/src/enginzoom.c
+++ b/src/enginzoom.c
@@ -143,6 +143,7 @@ short get_render_area_for_zoom(short zoom)
     // In low resolution, use even lower render area
     if (h < 400)
         rarea  = rarea * 4 / 5;
+    if (rarea & 1) rarea++;
     LOGSYNC("Render area %hd dt %d zoom %hd", rarea, dt, zoom);
     return bound_render_area(rarea);
 }
```
does it make it always correct, or always incorrect?

**Comment by geist22** [comment]
It still looks incorrect with this change.

**Comment by geist22** [comment]
This doesn't work either for me.

**Comment by mefistotelis** [comment]
Oh I see, the value is now at its max so this does not change anything. We have to modify the bounding function instead:
```
diff --git a/src/enginzoom.c b/src/enginzoom.c
index bd40d03..f8683fc 100644
--- a/src/enginzoom.c
+++ b/src/enginzoom.c
@@ -118,6 +118,7 @@ short bound_render_area(short rarea)
         rarea = RENDER_AREA_MIN;
     if (rarea > RENDER_AREA_MAX)
         rarea = RENDER_AREA_MAX;
+    if (rarea & 1 == 0) rarea++;
     return rarea;
 }
 
```

Doing that produces a difference for me, between `(rarea & 1)` and `(rarea & 1 == 0)`. Still not sure which one is correct.

**Comment by geist22** [comment]
Yes, doing it like this worked.

**Comment by mefistotelis** [comment]
Pushed a fix. It should now also be harder to see terrain bound after lowering the camera with `Insert` key.
