### ISSUE TITLE
bug: Item objective in Phoenix In Flames cannot be completed on mission restart

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#155]
On the Eurocorp mission Phoenix In Flames (mission index 21), the player has to get an item from the zealot base and bring it back to the start area. This works fine if completed first time. However, if the player gets the item from the base and then restarts the mission, in subsequent attempts the mission can't be completed, as the objective does not register as complete even though the game acknowledges the player has the item. 
Video here: 
https://youtu.be/qjjhDVCTBko

**Comment by mefistotelis** [comment]
Should be fixed with:
https://github.com/swfans/swars/commit/3ef76ede4fd374695a98669f4790286ac161af9e

**Comment by Moburma** [comment]
Yep, that seems ok, I played through, got briefcase, restarted, and was able to do all again to completion.
