### ISSUE TITLE
bug: Lighting on Rome map moves out of sync with light source

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#156]
I've only noticed this affecting the Rome map, but might affect others too. If the camera is moved, the light from fires moves out of sync of the actual fire itself, and in fact scrolls away to the opposite direction of the camera. See video here:
https://youtu.be/jgYd1lBYL9o

This seems to have occured since [#1208](https://github.com/swfans/swars/commit/f519f4b3e336416b6eed4d3700e6751fcb0177c2).
It occurs at all screen resolutions and also in low res mode.

**Comment by mefistotelis** [comment]
looks like `super_quick_light[]` array is filled in different places than rendering functions expect it to be.
The positions match only for very low RENDER_AREA_MAX, ie. 30.

**Comment by mefistotelis** [comment]
Should be fixed now.

This is likely original game bug - but draw distance in original was 30, so it was happening only close to one specific border of the map.

**Comment by Moburma** [comment]
Yep, that seems fine now.
