### ISSUE TITLE
bug: On levels with one character, possible to switch to random NPCs using the numpad

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#160]
On levels with only one player character (e.g. De Saxo or Agent Wu levels), it's possible to change to non-existent other characters using the the number keys.

This is an original game bug, brought to my attention by a [guy on Youtube](https://www.youtube.com/watch?v=S8QY-dNRQQ8).

Basically on levels where the player only gets one playable character, there is a chance the game will map the other characters onto other Things in the level. They don't appear in the agents list, but using the number keys you can switch to them. Reportedly this sometimes maps them to random characters in the level, but I've only seen it map them to buildings. 
This doesn't always happen, sometimes you can load one of the levels and it will behave as expected and the keys do nothing, other times it maps the other 3 characters to buildings. If you double tap the key the game will jump to the Thing in question.
A mission where I've definitely had it happen is the Eurocorp mission The Special Agent (mission index 9).

**Comment by mefistotelis** [comment]
Should be fixed with:
```
swars: Always set all MyAgent pointers
```

**Comment by Moburma** [comment]
Yep, that seems fixed now.
