### ISSUE TITLE
Lighting changes when starting the same mission two consecutive times

### ISSUE THREAD

**Issue by geist22** [swfans/swars#161]
Also happens in the original game.

If you start a mission, abort, and start the same mission again, the lighting changes, most notably the shadow at the edges of the map is gone:

![01](https://github.com/swfans/swars/assets/107389189/335f18d4-0eec-415c-b064-9138be47a67a)

![02](https://github.com/swfans/swars/assets/107389189/044f2a6a-a563-43f0-80b9-4cc391597ead)

**Comment by mefistotelis** [comment]
Should be fixed with:
https://github.com/swfans/swars/commit/112bd7680c6c060264f7d8999c06ade5387099f4

**Comment by geist22** [comment]
Confirmed working.
