### ISSUE TITLE
bug: Pair of vehicles can stop on collision with each other

### ISSUE THREAD

**Issue by mefistotelis** [swfans/swars#163]
Some road geometries allow for vehicles to be locked on each other:

![synII150](https://github.com/swfans/swars/assets/11463396/7b56115b-8937-4b70-be26-4e1b584edd5c)

Even on maps with standard layout, it is possible to cause a lock if any drivers have patrolling duty and happen to exit for a patrol just at the crossroad. Getting back to the car while another car is passing can then lead to the collision lock.

If cars are locked on each other, the one on the right should be allowed to continue forward. The one on the left could also back off a bit.

Mission with reproduction: `-m 0,21`.

I'm not sure if this also happened in original game.

**Comment by geist22** [comment]
I've witnessed traffic jams getting caused at two intersections in Phoenix in the original game. The one you posted, and one next to the bank:

![01](https://github.com/swfans/swars/assets/107389189/b6304d6c-bbcf-40e7-8126-cb5809e1074c)

Here it's caused by the two small vehicles on the bottom left. Usually one coming from the left and another from the right doing a right turn.

> Even on maps with standard layout, it is possible to cause a lock if any drivers have patrolling duty and happen to exit for a patrol just at the crossroad. Getting back to the car while another car is passing can then lead to the collision lock.

I've never seen this, though this is such a specific scenario that it will rarely ever happen during regular gameplay. You'd probably have to make a custom map/script to cause this to happen.

**Comment by mefistotelis** [comment]
>>    Even on maps with standard layout, it is possible to cause a lock if any drivers have patrolling duty and happen to exit for a patrol just at the crossroad. Getting back to the car while another car is passing can then lead to the collision lock.
>
>I've never seen this, though this is such a specific scenario that it will rarely ever happen during regular gameplay. You'd probably have to make a custom map/script to cause this to happen.


It happened to me on Matochkin Shar map, though not sure which mission it was. Possibly it was one of the additional missions, not from the main campaign.

The police car itself was able to eventually escape the jam (at least for some time), because each time he went on patrol and returned to said car, it moved forward a bit.

**Comment by mefistotelis** [comment]
> If cars are locked on each other, the one on the right should be allowed to continue forward. The one on the left could also back off a bit.

There already is such mechanism (though it selects the stopped vehicle based on thing offset rather than left/right). The reason for the jam is more complex. While one of the culprit vehicles is waiting due to collision, the other does not. I don't yet understand the reason why the other vehicle is stopped.

**Comment by mefistotelis** [comment]
Workarounded.
There are no longer blockades now, but it is possible that this change increases the chance of two vehicles going through each other:
https://github.com/swfans/swars/commit/7b67383a56bf3dffe30faf336a884741477f7b4a

Instead of this, vehicles should stop earlier when another is on the crossroads. But that would require fully understanding the links between crossroad nodes, and how to use them to check where the other vehicles are. Currently I don't understand enough to provide a proper fix.

**Comment by mefistotelis** [comment]
I think this can be closed. The issues with vehicles shifting through each other should be addressed in a separate bug.
