### ISSUE TITLE
Starting a new game too many times causes corrupt save files

### ISSUE THREAD

**Issue by geist22** [swfans/swars#165]
Original game issue.

The things you find in this game...

So I was repeatedly starting new games to reroll the names of my agents - turns out that if you do it too many times, it will lead to corrupt saves.

The way it works is that after starting a new campaign more than a certain number, I believe it's around mid 30's depending on the number of missions per campaign, missions starting from the back end of the campaign will have either "no objective" or "mission complete" (with no way to complete them) replacing their objectives, and working its way back to the earlier missions the more often you restart. After starting around 45-48 times, the broken objective will be at the 2nd or 3rd mission, while corrupting the first mission takes quite a lot more (I didn't count those).

**Comment by mefistotelis** [comment]
Wow.. this does reproduce..

The test patch to repeat login/logout 50 times:

```
diff --git a/src/game.c b/src/game.c
index 61ef111..960c96d 100644
--- a/src/game.c
+++ b/src/game.c
@@ -10479,6 +10479,8 @@ void show_load_and_prep_mission(void)
     stop_sample_using_heap(0, 122);
 }
 
+extern struct ScreenButton sysmnu_buttons[];
+
 void show_menu_screen(void)
 {
     switch (data_1c498d)
@@ -10820,6 +10822,49 @@ void show_menu_screen(void)
         wait_for_sound_sample_finish(111);
         stop_sample_using_heap(0, 122);
     }
+
+    static int aa = 0;
+    if (aa < 50*64)
+    {
+        switch (screentype)
+        {
+        case SCRT_MAINMENU:
+            if ((aa % 64) == 0)
+                lbKeyOn[KC_RETURN] = 1;
+            break;
+        case SCRT_LOGIN:
+            if ((aa % 64) == 20) {
+                login_name[0] = 't';
+                login_name[1] = '\0';
+            }
+            if ((aa % 64) == 22) {
+                lbKeyOn[KC_RETURN] = 1;
+            }
+            break;
+        case SCRT_99:
+            if ((aa % 64) == 28)
+                lbKeyOn[KC_F4] = 1;
+            break;
+        case SCRT_EQUIP:
+            if ((aa % 64) == 32)
+                lbKeyOn[KC_SPACE] = 1;
+            if ((aa % 64) == 37)
+                lbKeyOn[KC_F1] = 1;
+            break;
+        case SCRT_NETGAME:
+            if ((aa % 64) == 46)
+                lbKeyOn[KC_SPACE] = 1;
+            if ((aa % 64) == 49) {
+                lbDisplay.MMouseX = sysmnu_buttons[5].X + 1;
+                lbDisplay.MMouseY = sysmnu_buttons[5].Y + 1;
+                lbDisplay.MouseX = lbDisplay.MMouseX;
+                lbDisplay.MouseY = lbDisplay.MMouseY;
+                lbDisplay.LeftButton = 1;
+            }
+            break;
+        }
+        aa++;
+    }
 }
 
 void draw_game(void)
```

After the 50 repeats:
* log in as Eurocorp
* pass mission 1 (mail 0)
* enter mission 2 (mail 1) - the objective will be invalid

**Comment by mefistotelis** [comment]
Should be fixed with:
[swars: Several unifications around mission state slots](https://github.com/swfans/swars/commit/42e1a320e995c23464d00575314a38aa8ff1241d)

**Comment by geist22** [comment]
Did a quick test, works for me so far.
