### ISSUE TITLE
bug: Enemies in Pre-alpha levels always drop an extra corrupt item when killed

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#166]
When any character is killed in a pre-alpha level, an extra junk item is dropped in addition to their weapons. This includes civilians.

![](https://i.ibb.co/0DsvLL4/Desktop-Screenshot-2024-05-14-21-40-12-47.png)

Not sure of the exact build where this began as they're not up for download any more, but it occurs in build 1873, and does not happen in 1830. The bug actually changed over time, at this point it would give an item using the capsule icon (used for skins), but now it's shifted to just a black corrupt icon as per screenshot.

**Comment by mefistotelis** [comment]
Would be easier to repro with example mission provided.

**Comment by Moburma** [comment]
As far as I can tell, all ones with pre-alpha levels.

Examples:
3,4
3,19
3,67

3,26 is intesting as you actually start with the item in your inventory

**Comment by mefistotelis** [comment]
Looks like it's already fixed, then.
(seeing the issue, I immediately noticed a suspicious line within the thing refresh function)

**Comment by Moburma** [comment]
Yep, that seems to have fixed it. The exception is still 3,26, I assume it's something to do with the code to insert an agent when there is no one in the player group.

**Comment by mefistotelis** [comment]
> The exception is still 3,26

Oh right, I had `--level-deep-fix` enabled so didn't see the issue there.
