### ISSUE TITLE
Movement getting stuck

### ISSUE THREAD

**Issue by geist22** [swfans/swars#179]
When moving through certain areas, such as near the map border/unpassable terrain, there's a chance your agents will get into a state where moving is no longer possible, though they can still shoot. Left-clicking will no longer show the "move" animation on the cursor, so it looks like rather than the agents being unable to move, the command itself is no longer working. The issue persists for the rest of the session until the entire game is restarted.

To reproduce, in `-m 1,85` try moving though the narrow back path between the wall of the enemy base and the map border. I could semi-reliably reproduce the issue by teleporting my agents to the other side of the water (where the militia with LR Rifles patrol) and moving in and out of the path around the corner.

I've tracked down the issue to https://github.com/swfans/swars/commit/94218fa9386302c38125fcf7873c60dfa7e81743.

**Comment by mefistotelis** [comment]
I see the issue.

LMB and RMB stops allowing to specify target on map. But LMB+RMB still works. Also switching to another agent and making him move a little "fixes" the first agent.

The wall near map edge for reproduction is on the separated island.

Looks like an issue with map coordinates update.

**Comment by mefistotelis** [comment]
Should be fixed with:
[swars: Switched types of map coords converted from mouse pos](https://github.com/swfans/swars/commit/7e0c09b79a4a677bced932b148fed593477387ee)

**Comment by geist22** [comment]
Seems to work.
