### ISSUE TITLE
Explosions light up out of bounds areas

### ISSUE THREAD

**Issue by geist22** [swfans/swars#180]
Out of bounds areas lights up white during screen effect of explosions:
![01](https://github.com/swfans/swars/assets/107389189/1b5a2000-5c74-478b-b8db-09f78a5bdcd8)
![02](https://github.com/swfans/swars/assets/107389189/245fa9b1-5d3c-4f22-9c29-07792713b5ec)

Original in DOSBox for comparison:
![03](https://github.com/swfans/swars/assets/107389189/2fb54c65-6f44-4827-b09b-ce09deb08d3b)

Hard to say when it started, out of bounds areas seem to have been affected by quite a few recent commits.

**Comment by mefistotelis** [comment]
Already there in 0.3.6.1830.

**Comment by mefistotelis** [comment]
Should be fixed with:
`swars: Disable suspicious color table fixups`

**Comment by geist22** [comment]
Yes, works.
