### ISSUE TITLE
bug: Chromotap doesn't work on Unguided player characters

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#189]
This is an original game oversight, likely because the unguided campaign was never finished so this never came to light. 
Basically, if a level with unguided as the player characters is played, the Chromotap weapon doesn't work correctly. When the "soul" is harvested from NPCs, they actually **cause shield damage** to the character receiving them instead of boosting the shield. It also wrongly strips energy from the actual player characters themselves when first used instead of only NPCs. This makes the Chromotap useless for the unguided.

Reproduction: start any unguided level (e.g. -m 2,1), use cheats to get chromotap and equip.

**Comment by mefistotelis** [comment]
I don't think I understand the problem.. the returning "soul" activates your shield for every faction. It still increases the "red bar", allowing to double your health.

Though I just noticed after you first use it, it gathers "souls" of your agents? I don't think that was intended..
(I'm actually not sure if gathering "souls" of living people was intended at all, but that's another discussion..)

**Comment by Moburma** [comment]
I'm sure I tested it ages ago and had this problem, and I was testing it last night and thought I saw the same, but checking again now, it DOES work normally, what the hell am I talking about! I was sure it was not filling the red bar at all for them, but err, it is!

But yeah, I guess to salvage a clearly wrong bug report, the stripping your own people's energy is likely not intended... (the soul thing is half joking - the internal name for it is "soul gun" so I think they **did** mean it as sucking away people's souls, even if just a basic way to explain the game concept, they weren't going to call it that in the final game). Sorry, maybe I should just close?

I do get the impression this weapon was never really finished properly, and it's not much use in the end so few people would even notice.

**Comment by mefistotelis** [comment]
Well, there are several problems with this weapon, so I think we should have several "issues" for it:
* Should not work on your agents
* Should be more configurable by INI file - whether it works only on corpses, HP gathered from each person, whether it activates the wielder shield
* Should stop gathering after red bar if filled, to avoid overflow

Feel free to create separate issues for these.

**Comment by Moburma** [comment]
Will log as actually accurate separate issues...
