### ISSUE TITLE
Bugged combat behavior

### ISSUE THREAD

**Issue by geist22** [swfans/swars#193]
Since https://github.com/swfans/swars/commit/65c5e4ba2fea2712bb3e4f76eeea6776f99687b2 there are several bugs that happen when my agents get into fights:

1. The minimap disappears
2. Agents get ungrouped and their health bar appears empty
3. Agents start to move/shoot on their own
4. Enemies seem to charge their weapons but don't usually fire

Tested on the Moon with Plasma Lances.

<details>
<summary>error.log</summary>
Error: Bflib: LbFileOpen: file does not exist: "data/tex06.dat"<br>
Error: Bflib: LbFileOpen: file does not exist: "conf\miss004.ini"<br>
Error: Bflib: LbFileOpen: file does not exist: "maps/map065.b&b"<br>
Error: SWars: fix_thing_command_indexes: Cmd136 = TNG_CMD_USE_VEHICLE target vehicle 126 not found<br>
Warning: SWars: init_mission_states: Mission 102 has no slot; initing anyway<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Error: SWars: draw_new_panel: Agent 1 unexpected flags<br>
Warning: Bflib: LbScreenReset: screen got reset while locked
</details>

**Comment by mefistotelis** [comment]
Should be fixed with:
https://github.com/swfans/swars/commit/c0b08f1d3c6fe7a9e279df251d56a13a4d5e1904

**Comment by geist22** [comment]
Yes, appears to be fine.
