### ISSUE TITLE
SDL2: Command line option -h/--help doesn't work

### ISSUE THREAD

**Issue by geist22** [swfans/swars#194]
Using the command line in Windows 10, the -h or --help option doesn't produce any output in the SDL2 version.

It works in the SDL1 version.

**Comment by mefistotelis** [comment]
Sholuld work since:
https://github.com/swfans/swars/commit/55347ac2c0b1059ca44040eaab32ec4486f3fbe8

**Comment by geist22** [comment]
Yes, I noticed that it's working now. Was just about to ask if this can be closed or if there's something left to be done.
