### ISSUE TITLE
SDL2: Window no longer centered after resize

### ISSUE THREAD

**Issue by geist22** [swfans/swars#200]
I'm using SDL_VIDEO_CENTERED 1 as system variable to have the window centered.

Whenever the window changes size or aspect ratio, i.e. for movie playback or custom resolutions in CONFIG.INI, it doesn't update the position and the window will no longer be in the center.

The SDL1 version does update the position so the window will still be centered after a change in size or aspect ratio.

**Comment by mefistotelis** [comment]
SDL2 doesn't react on this variable. A list of variables it uses is in this file:
https://github.com/zielmicha/SDL2/blob/master/include/SDL_hints.h

During window creation in bflibrary, I'm using `SDL_WINDOWPOS_UNDEFINED`. Details:
https://wiki.libsdl.org/SDL2/SDL_CreateWindow

**Comment by geist22** [comment]
I don't find much in the way of window position here.

I've tried changing the `SDL_WINDOWPOS_UNDEFINED `to `SDL_WINDOWPOS_CENTERED`, but it doesn't seem to do anything.

**Comment by mefistotelis** [comment]
> I don't find much in the way of window position here.

Yeah, it's not supported as an env variable. But you can change it in the sources.
SDL2 supports multiple windows per application, so I guess that was removed to avoid multi-window problems. Even though almost all SDL2 apps only use one window.

**Comment by geist22** [comment]
> But you can change it in the sources.

Yeah I'll do that, can you tell me how? To always have the window centered and re-align it after resolution or aspect ratio changed.
Right now, the window is partially off-screen when using a higher resolution, and you'd have to manually move it every time.

**Comment by mefistotelis** [comment]
> I've tried changing the `SDL_WINDOWPOS_UNDEFINED `to `SDL_WINDOWPOS_CENTERED`, but it doesn't seem to do anything.

Hm, this is unexpected. So I guess it only centers the window on first run, and you already have it centered then?

In that case, you need another call when the window is not re-created, after SDL_SetWindowSize(). And that call is:
https://wiki.libsdl.org/SDL2/SDL_SetWindowPosition

**Comment by geist22** [comment]
> So I guess it only centers the window on first run, and you already have it centered then

Yes, the window first starts centered by default (even with `SDL_WINDOWPOS_UNDEFINED`), but when it gets resized the position isn't updated. Starting the game with -q option to skip intro seems to load the intro even if it doesn't play, so the aspect ratio gets changed to 16:10 and then immediately back to 4:3 for the menu. Using the default window size and resolution this isn't problem, the menu stretches the screen vertically on both sides, while the width remains fixed.
When using a custom window size (I know, not officially a supported feature yet) by editing `LbScreenSetMinScreenSurfaceDimension(400)` in `display.c`, the height is fixed and the window shrinks horizontally for the menu on the right side only, putting the window too far to the left.
But this is also noticeable with an unmodified window size by changing resolution for menu or gameplay in `CONFIG.INI`, which extends the window to the bottom right, causing parts of it to go off-screen if the resolution is high enough. The window seems to be aligned on the top left corner, but only when using a non-default resolution or window size.

> In that case, you need another call when the window is not re-created, after SDL_SetWindowSize().

Alright, I've managed to fix the issues in every configuration I've tested with this. I'm only using windowed mode for now, though. 

We've had a short issue about centering the window before (https://github.com/swfans/swars/issues/50), but it wasn't done because there was a workaround for SDL1, which I've used since then. Because this doesn't work with SDL2, and the default behaviour looks undesirable, this might be a worthwile addition to the main repository.

**Comment by mefistotelis** [comment]
The default should be that Windowing System is responsible for finding a position.

For the centering issue - since that's something specific to SDL2, and SDL2 lacks the `SDL_VIDEO_CENTERED` variable support, we could add the feature using that variable - this way users could use the same way of centering for both SDL1 and SDL2.

So yes, I'd accept a change where we check the value from `SDL_getenv("SDL_VIDEO_CENTERED")` and if set to 1, we're centering the window on every mode switch.
