### ISSUE TITLE
bug: HUD and sprites corrupt after playing a short while in 1920 x 1080 custom resolution

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#208]
This started happening with https://github.com/swfans/swars/commit/6efb44ef19ed00f16170bda290019969693ab04c
Sometimes happens straight away, sometimes needs a few minutes to appear. Happens with different zoom levels and HUD styles.
corrupt lines start to draw across the HUD, and sometimes this then extends to sprites in-game as well. Occurs with the very latest commit (https://github.com/swfans/swars/commit/4a1ea9ff765eabe5650e603da932a392de59f524) still.

It doesn't seem to happen with lower resolutions, trying 640 x 480, 800 x 600 and 1280 x 720 all worked fine.

Example screenshot:

![](https://i.ibb.co/k5p6Yy3/Desktop-Screenshot-2024-10-02-21-48-03-64.png)

**Comment by Moburma** [comment]
Here's a video, if it helps at all:

https://www.youtube.com/watch?v=1d84xQePBEg

**Comment by mefistotelis** [comment]
Just fixed the poly_line - so it should no longer occur.

**Comment by Moburma** [comment]
Yep, that seems to have fixed it, thanks.

**Comment by NebularNerd** [comment]
I'm likely being dense but I can't see how to change the resolution, look at #15 I cannot find that line in the source. Which lines do I need to change to alter the resolution? I found `LbScreenSetMinScreenSurfaceDimension(400)` in `display.c` and that does change the window size while starting up, but then it just switches to a square window (at 1080 high for example) when I enter the level.

**Comment by Moburma** [comment]
> I'm likely being dense but I can't see how to change the resolution, look at #15 I cannot find that line in the source. Which lines do I need to change to alter the resolution? I found `LbScreenSetMinScreenSurfaceDimension(400)` in `display.c` and that does change the window size while starting up, but then it just switches to a square window (at 1080 high for example) when I enter the level.

Hi, please see the wiki here:
https://github.com/swfans/swars/wiki/Configuration-Files-Values

You don't need to change the source. Make you are using a recent build as well, very old ones did not support this feature.

**Comment by NebularNerd** [comment]
Thanks @Moburma 

Just built from the source yesterday for Win 11 and 1080 looks great, it's amazing to see how well it holds up after all these years (I started playing this when it came out on a 17" CRT), 1440 corrupts similar to your initial post and 4k currently crashes 🤣

But this is awesome progress for a port I've been following pretty much from its early Google Group days.

**Comment by mefistotelis** [comment]
> 4k currently crashes 🤣

You'd have to adjust `MAX_SUPPORTED_SCREEN_WIDTH` and `HEIGHT` for the 4K+ modes to have any chance of working.
But some polygons are bounded to 2048, so I wouldn't recommend widths above 1960.

**Comment by Moburma** [comment]
Another enhancement you might like is adjusting the zoom levels, as detailed [here](https://github.com/swfans/swars/wiki/Game-Modifications-%E2%80%90-Rules.ini). We know the graphics for the game were designed to be seen more zoomed out than they are by default, and it's also much more comfortable to play like this, especially in high res. I personally use
ZoomMin = 100
ZoomMax = 140
But have a play with the settings.

**Comment by NebularNerd** [comment]
> > 4k currently crashes 🤣
> 
> You'd have to adjust `MAX_SUPPORTED_SCREEN_WIDTH` and `HEIGHT` for the 4K+ modes to have any chance of working. But some polygons are bounded to 2048, so I wouldn't recommend widths above 1960.

This explains the issues at 2560x1440, recompiled at 4k just for a laugh and while it's very clearly borked due to the bounding issues (and 486 grade performance), I can at least watch Ghost in the Shell at 4k now 😀

![Syndicate Wars Port 10_11_2024 10_11_31](https://github.com/user-attachments/assets/8174e457-cd6d-4757-bd00-698a3d5bf441)
