### ISSUE TITLE
bug: Tank turrets do not start pointing the same direction as their base models

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#217]
It's debateable if this is really a bug or an enhancement, but it's noticeable that the turrets on tanks and do not face the same way as how their tracks are set to face in a level on level start. What is particularly noticeable is that they all face towards North in a level, so presumably simply have the same default facing value.

Why this is not desirable is a) it looks strange when every tank is looking the same way (see level C065L005.DAT), but more importantly b) some vehicles were deliberately placed a certain way and this effect is lost due to the turret not matching this direction.

The most striking example of this is the Columbo mission for both campaigns. The mission starts with a pair of claw mechs right at the start. As the entire mech (aside from the legs) is the turret, they both face away from the player start position due to the lack of a position angle on turrets. 
However, these two units are placed in a very particular way. If the full mech unit is deliberately switched out for just the turret model only, it gets correctly aligned in the level and the intended effect is revealed:

![](https://i.ibb.co/K2sWwLN/Desktop-Screenshot-2024-06-08-17-04-10-12.png)

The mechs are supposed to be in alignment with the rows of zealots making up the head of the arrow formation pointing to the middle of the level, as demonstrated by the hacked unit on the left. The mech on the right is how this normally appears in the game, with the turret pointing to the default angle, entirely away from where it seems it was intended for them to be looking. 

Therefore the desired fix would be for the turret object to inherit the initial facing angle from the bottom Thing of the tank.

**Comment by mefistotelis** [comment]
That was easier than expected.. there already was a code to rotate the turret, but it had copy-paste errors - it was re-computing the lower part angle for a second time.

So, should be fixed with " swars: When loading a level, restore tank turret angle".
(though the angle for the level you presented doesn't seem to match your expectation)

**Comment by Moburma** [comment]
Closing as fixed
