### ISSUE TITLE
bug: Player characters are drawn over any building they go inside

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#220]
Happening since https://github.com/swfans/swars/commit/5b6b4100502f6e18451de17ef538390ef8ae8139
When the player's units go inside a building, they are visible through the walls, their character is drawn over the top of the walls instead of hidden by them.
To reproduce, just go inside any building on any map.

Example screenshots:

![](https://i.ibb.co/ZHNmWc3/Desktop-Screenshot-2024-11-18-18-03-43-10.png)
![](https://i.ibb.co/H7vsBjp/Desktop-Screenshot-2024-11-18-18-03-51-87.png)

**Comment by mefistotelis** [comment]
Interesting bug.. shouldn't that be used to make the infrared mode useful?

**Comment by Moburma** [comment]
> Interesting bug.. shouldn't that be used to make the infrared mode useful?

Yeah, that would be good. One thing that is interesting is the odd design choice where certain buildings in the game are completely opaque and you can never see inside them, even with the B key. Might be useful there, where you can then use infrared to actually see people in those buildings (at the cost of weapon energy)?

**Comment by mefistotelis** [comment]
Oh, also - mapmaking hint:
In order to have a person start invisible inside building (not on radar and not able to reveal by abusing the depth), you need to raise the "InsideBuilding" flag for it.

Or put it outside and make it walk into the building - passing through doors sets the flag.

**Comment by Moburma** [comment]
> Oh, also - mapmaking hint:
> In order to have a person start invisible inside building (not on radar and not able to reveal by abusing the depth), you need to raise the "InsideBuilding" flag for it.

Getting a little bit off topic, but 
TgF2_Unkn01000000 = 0x01000000,
Makes peeps invisible, if you didn't know already.
