### ISSUE TITLE
Enhancement: Option to disable scientist deaths

### ISSUE THREAD

**Issue by geist22** [swfans/swars#38]
This mechanic randomly screws you over and the player has absolutely no control over it. Maybe the developers didn't want you to have 30 scientists, but when this happens to me, which is frequently, I just feel the need to replay the last mission again, which is often frustrating, especially for long and difficult missions. In the beginning when you only have few scientists, it can be crippling even.

It would be great if there was an option to disable this entirely.

**Comment by mefistotelis** [comment]
Note that you can easily get any number of scientists from the recurring missions, like this one:
http://syndicate.lubiki.pl/swars/walkthrough/swars_lev004.php

But yeah, I agree - this mechanic should be better explained, and an option to disable it would be nice to have as well.

There could be a warning in the research screen that overworking could lead to deaths.

**Comment by geist22** [comment]
> Note that you can easily get any number of scientists from the recurring missions, like this one:
> http://syndicate.lubiki.pl/swars/walkthrough/swars_lev004.php

I know, but aborting optional missions and keeping the rewards is kind of a bug by itself, so I don't want to use it. The mission with the orbital lift has some weird stuff like that too, where you can return to the menu after a failed mission to advance research time.

**Comment by geist22** [comment]
Syndicate just advanced research in realtime, with it being faster during missions. Of course that came with its own problems, if you wanted to you could just go AFK and the research would keep running.

Randomized research progress (2-5 days per mission, I think) is another RNG element that can be frustrating. You really want that Plasma Lance researched after that mission, but then the game says you got only 2 days mission time, too bad for you!

But that's another thing for another time. I'm kind of a purist so I don't want to have the game redesigned and changed too much from its original form, just have the option to have some of the more frustrating things adressed.

**Comment by mefistotelis** [comment]
Possible implementation: INI-like config options, either within campaign config file or separate `rules.ini` file.

```
[research]
; Base amount of research points generated per day by 1 scientist at 1% funding
BasePointsPerDay = 256
; Amount of scientists per group; each subsequent group can generate up to half of the research previous group generated
ScientistsGroupSize = 4
; Chance of a lab accident resulting in death; 1-2 scientists can die if an accident happens; set to 0 to disable accidents
ScientistDeathChancePermilePerDay = 10

[persuade_awards]
AGENT = 1000
ZEALOT = 1000
PUNK_F = 150
PUNK_M = 150
BRIEFCASE_M = 100
WHITE_BRUN_F = 100
```

**Comment by geist22** [comment]
I would have thought for this to be in a global config file. If you want to introduce some hardmode campains later as said in the thread with the moon robot, maybe override it on a campaign basis with special rules, akin to mortal games. But I really do not like this mechanic, because it is outside of the player's control.

Incidentally, can other options be made global too? The game has an ini file in the savegame folder, but it's weird. It only works for the savegames and new games under that name, and by default other new games start with VGA resolution, default agent coat color and have to redo all the keybinds again, which is pretty annoying.

**Comment by geist22** [comment]
The credit reward for persuading people seems to be broken in the port right now.

**Comment by geist22** [comment]
> For default options, in one of recent changes I introduced "Anon" as default login name - so if you copy your file to `ANON.INI`, it should load it at startup. (previously there was no default name, so the game tried to load `.INI` file, which was bad).

This doesn't seem to work properly. It loads at startup, so it skips the projector animations at the start (with fast projector) when you're not logged in, but as soon as you make a new user it goes back to the defaults (not from the `ANON.INI`, but actual game defaults like VGA resolution, no keybinds etc.).

**Comment by mefistotelis** [comment]
File `rules.ini` now has an option `DailyScientistDeathChancePermil`.
Setting it to 0 will disable the deaths.
