### ISSUE TITLE
Enhancement: Support for pre-alpha level files (file versions below v 15)

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#53]
The final game includes a large number of levels from the pre-alpha versions of the game. These use a different data structure to level file version 15 on wards that the game can play. I managed to create a simple [script ](https://github.com/Moburma/SWLevelConvertor)to move identified data around in these files to make them playable, but it would be good to have support in the game itself if possible. I had hoped to get this better written up by now, but not had time, but I will make another attempt to properly understand what data is where in these old level files. My previous understanding was not complete, but it was good enough to play most pre-alpha levels without any obvious issues.

I will try and provide updated and coherent structure data for the version 12 files, with the positions documented for the variables the game needs to load the needed data that v >15 use.

**Comment by mefistotelis** [comment]
The documentation would be great, thanks.

In your script, I see that you did not separated the fields depending on thing type - besides the condition on MaxHealth.
These should probably be separated.

**Comment by Moburma** [comment]
Yes, I did it very quick and dirty, and stuipidly didn't write down down a definitive set of what is where. Also, I already listed all levels based on version, with their timestamp you can see when each level format can and went:
https://tcrf.net/Notes:Syndicate_Wars_(DOS)#Level_File_Versions

Here is an early version of the basic Thing struct:

struct Thing
{
    short Parent;
    short Next;
    short LinkParent;
    short LinkChild;
    ubyte SubType;
    ubyte Type;
    short State;
    ulong Flag;
    short LinkSame;
    short Unknown1; // This actually looks like Parent data for vehicles
    short Radius;
    ushort Unknown2;
    long X;
    long Y;
    long Z;
    short Frame;
    ushort StartFrame;
    short Timer1;
    short StartTimer1;
    long Unknown3;
	short Unknown4;
    ushort ThingOffset;
    short Unknown5;  // has more data in it, need to look at more closely
	short Unknown6;
    short Unknown7;
    short Unknown8;
    short Unknown9;
	short Unknown10;
    short Stamina;     
    short MaxStamina;  
	short Unknown11;
	short Linksamegroup;
    short Unknown12;   
    short Unknown13;  //Clearly some kind of NPC stat, uniform for each type of NPC. No corresponding pair value though
    union {
        struct TngUObject UObject;
        struct TngUMGun UMGun;
        struct TngUVehicle UVehicle;
        struct TngUEffect UEffect;
        struct TngUPerson UPerson;
    } U;
};

The above is for a version 12 file. As far as I can remember I didn't find any obvious differences between versions 9 - 12, but that of course does not mean there aren't any.

I found that actually the stamina values seem to be here after all (in what would become the PTarget field), also identified some other data I was ignoring before I need to go back and look into in more details. I will also do UVehicle and UPerson as well.

One other thing on the level files, I believe everything else just works if taken as-is (i.e. command data, group information, items), it's just the Thing data that seems different. You'll also want to run them as version 16 files, as they do not have the Armour field populated, which version 17 needs (otherwise all vehicles die from one shot!). 16 and lower use Maxhealth for vehicle health.

I documented some of this in https://tcrf.net/Notes:Syndicate_Wars_(DOS)#Level_File_Versions but stupidly never went back and detailed my findings for the early files... 

My understanding of the old Things format was only about 75%, but enough to make all levels fully playable with only minor bugs (e.g. the level Talks Ambush has weird stuff happen when you have to pick up the weapon items from the floor, the objective overflows onto other scenery objects, but it was not clear why it did this and if it was a conversion bug or not). 
I never did figure out the group relations data, I had a hunch it would just be one of the 40 bytes for each of the 40 groups and some value representing the relationship, but it's definitely not that and I never went back to figure it out.

I was surprised that looking at the recent level loading code you redid it seemed there WAS some basic compatibility for pre-alpha levels still left in the code, I wonder if they deliberately removed a lot of in the end?

**Comment by mefistotelis** [comment]
> there WAS some basic compatibility for pre-alpha levels still left in the code, I wonder if they deliberately removed a lot

It doesn't look like anything was removed to me. They tried to keep compatibility, but it was not a task which was supposed to take too much time. So when it broke due to thing changes, noone investigated. For the whole development time they were trying to make things compatible by adding conditions where they changed something.

Either during refactoring of the Thing struct they had more pressing matters than old formats, or when adding changes they sometimes forgot that the Thing affects level format.

It looks to me that the old Thing didn't had an union in it - there was just one struct with fields added as they were needed.

**Comment by mefistotelis** [comment]
Let me know what else should be changed there:
https://github.com/mefistotelis/swars/blob/bbc29ef7af4a2f60e577a7eae6b14a421bb5f4da/src/thing.h#L380

**Comment by Moburma** [comment]
Ahh the pre-alpha uses that too? That's very interesting. I've not got much free time at the moment, very busy with work, but I am on holiday next week so hopefully can spend more time on it. Something I just realised now - the Max/Stamina variables I identified above are only in the version 12 structure (which is probably why I hadn't noticed them before). They are not there in the version 9 or 11 structures. I hadn't spent much time looking for differences between the versions, so there's one.

**Comment by Moburma** [comment]
I'm pretty sure the unions are used, there's clearly different usage of the same bytes in the file between vehicles and people, I just mainly focused on the people data when writing it up.

**Comment by mefistotelis** [comment]
I found `PersonComCur` (index in the `game_commands[]` array) at 0x5E in the Alpha. So I still believe the no unions hypothesis.
(though it also means that differences between versions may be substantial)

**Comment by Moburma** [comment]
Yes, I'm not finished yet though. I'll commit once more complete. Hopefully have time to do it this evening. I also updated my level reader tool to assist.

**Comment by Moburma** [comment]
I submitted a pull request now. First one I have ever done, so apologies if anything is wrong. Still quite a bit to work out, mainly around vehicles, but I have more of the core values in, so a lot better than nothing. I actually wonder if attributes should just be TngUnkn unless sure of what they are, as some are just assumptions/leftovers rather than proven correct. 
I actually initially made another structure for v12, but there don't seem to be enough (identified) differences yet to be worthwhile. The biggest one I have found so far is that file versions 9 and 11 do not seem to have any Stamina data in them, this seems to have been a version 12 innovation.
Also need to test more of the above with my old convertor script.

**Comment by Moburma** [comment]
I went through a load of vehicle stats this evening - you were right, after spending a long time looking these up, they were mostly exactly the same as the V4 stats you found. Seem to diverge towards the end though. I'm not about much tomorrow but will try and get more done and commit in the evening, current update is in my branch.

**Comment by mefistotelis** [comment]
Ok. After your changes, I will update the code to properly assign the values of same names.

**Comment by Moburma** [comment]
Updated now, I think that is mostly as far as I can get comparing actual data against final level files. What is left mostly has no data in it in the early levels I've checked. For those values you identified for V4 but are unknown here, it probably makes sense to use the V4 value, they have been mostly correct so will probably continue to be so.

**Comment by mefistotelis** [comment]
Ok will take your findings and then mix with the V4.
Thanks!

**Comment by mefistotelis** [comment]
Did it. Merged all we know, commented each field for which we had any comment, and provided source of research (so either my RE of Alpha, or your comparing binary data).

Fields without comments should be treated as just guesses.

What bothers me is that we don't have cyborg mods copied. Since the concept comes from first Syndicate, I'm sure it was already defined in Alpha. Maybe it's possible to find..

If you have any remarks, or I made any mistake, or you just have a comment for another field - please write or make a PR.

**Comment by Moburma** [comment]
Really fantastic, I've been playing levels with it and they work great. along with the new campaign editing ability, I've made this video of one of the totally cut levels a) running without conversion and b) with custom objectives:
https://www.youtube.com/watch?v=zXYe4zoM7Qw
What you can't see in the video is that the objective is to stop the soldier in the big dropshop car from escaping up the freeway to a flying car that he uses to go to the edge of the map. I've put a fail state in for if he gets to the map edge (GAME_OBJ_MEM_G_ARRIVES), and it's working great. This also seems to fix a bug I had with my old convertor script where the unguided on this level would change to Eurocorp if you restarted the level (probably some sort of overrun from all the bad data I was passing!).

Is the v4 structure not in the map files (the level files definitely only contain group names) ? I had a look now but couldn't see where it starts and ends, but it must be in there (or at least something is), as saving maps in the editor does reflect the Thing state once loaded. I tried removing all people and saving/comparing, but it changed an insane amount of data and not in one place like I hoped. 
As an aside the pre-alpha maps look a lot like the "old" PS1 maps, so I would not be surprised if they don't use the same level/map format. The newer PS1 levels (i.e. the ones that actually work) definitely use the standard 216 byte final standard for Thing data. I might try and rip the PS1 exclusive levels from the maps one day (although they are not very interesting).

**Comment by mefistotelis** [comment]
> Is the v4 structure not in the map files?

I don't think I ever looked in detail how the pre-alpha saves the maps.

> The newer PS1 levels (i.e. the ones that actually work) definitely use the standard 216 byte final standard for Thing data.

You mean the standard 168-byte, same as final on PC? 216 byte is the old thing format, the one we're converting to 168.

>  I might try and rip the PS1 exclusive levels from the maps one day (although they are not very interesting).

If we make more campaigns out of levels playable on PC, then using PSX maps would be an interesting twist sometimes - no rail, etc.
For PSX levels - not sure if we can find anything exciting there.

**Comment by mefistotelis** [comment]
The video - near the end a civilian is escaping looking like infinite zap effect. Some fixes are still clearly necessary.

If you want to focus on making the Unguided maps into a proper campaign, you may open another "issue" to track the work on that. (actually we'd really need more - for levels, text briefings and graphics.. but for now we can't provide more than levels).

Also, I added all the levels not included in the original `miss000` to a separate file, `miss003`. It's not selectable in "new game", but you can play the missions using command line param, ie. `-m 3,4` to play map 4 (from file `miss003.ini`).

**Comment by Moburma** [comment]
Yes, I will make an Unguided campaign topic shortly. Do you want fixes passed up for the campaigns so far? Specifically I have some of the Unguided campaign, mission 64 has the wrong level set in the final game, the objectives perfectly match level file  c003l007.d1 and are wrong for the level actually set in the slot. Also mission 65 (and its clone) needs the target group changed from 5 to 3 to play properly. I've also started putting in the totally cut levels and giving them objectives, like the one above.

**Comment by mefistotelis** [comment]
> Do you want fixes passed up for the campaigns so far?

Yes. Incremental changes is a generally used practice in any software development today.

**Comment by mefistotelis** [comment]
I cannot find mods in the old Thing based on alpha code. Maybe these should be reconstructed from something else? ie. health  /shield / weapon energy? Are these values even differentiated in the old files, or always the same?
If they're the same, then we could set mods based on tier of weapons used in a level.

And a second subject: I think we may have PersonGroup at 0x4B (from Alpha code). That would mean what's identified at 0x56 might be effective group. Can you look at the binary data and let me know whether that's possible?

**Comment by Moburma** [comment]
Yep, looking at it you're correct, I was stupidly thinking it would be a short to fit in with the other data patterns, but it's just that one byte. The values match the currently identified group data exactly. 
One thing I notice is that in the early formats the effective group does not use 99 for vehicles like the later data formats do. Do you know what effective group does? Does it updated based on faction/relation changes or something (like if one group becomes hostile to another)?

**Comment by mefistotelis** [comment]
> Does it updated based on faction/relation changes or something

A Person can change effective group by being persuaded. This way if the persuadertron wielder dies, or disruptor is used - the previous group can be restored.

Thanks for checking that.

Maybe we should update the group for vehicles. Having a vehicle amongst your agents wouldn't probably cause any major issue, but would look strange in the scanner.

**Comment by mefistotelis** [comment]
Which `fmtver` have incorrectly set Vehicle groups? I see that in `-m 3,20` and that level has v17. When cops exit their cars, the cars start being visible as your agents on the scanner map.

**Comment by Moburma** [comment]
Hmm, it's interesting actually, a lot of levels just plain don't seem to have a different group set for the vehicles. 
I hadn't notice this issue previously, just the fact that vehicles in group 0 (player group) are inconsistently added to the effectivegroup of 99. In later levels  (>15) they generally are always set this way, but sometimes they aren't. Going back to format 15 most are NOT set this, way, but at least one level actually is already. Older levels don't seem to bother. 
I'll have to do some experimenting to figure out if there is a specific level version that's causing the empty car bug.

**Comment by mefistotelis** [comment]
Looking at the code, the game only loads definitions of 32 groups from level file. So setting group ID to 99 really means setting it out of range. Not sure if that's a good idea.

**Comment by mefistotelis** [comment]
In first multiplayer mission (`-m 99,1`, I just renamed the MP missions file) there are two cars on top of each other which are clearly supposed to be a tank. Do you think we should fix that in code? does this happen in other missions? This one has `fmtver=17`, so less related to this thread.

If it's a single case, then should probably be fixed on the level rather than in code..

**Comment by Moburma** [comment]
Sorry, been a bit busy lately. I think we should avoid fixing things like that in code, I was really surprised how much was already being bodged that way in the original code. Plus if we did fix the level files (which seems to be the way to go), then people can even use them in the original versions if they really wanted. The only problem is then potentially hosting game assets, but then I don't imagine a few levels for a dead game is a big deal.
Also thanks for the documentation of the group behaviours, I had a hunch it worked that way based on the pre alpha editor, but never worked out the particulars. I will try and make some kind of basic level editor, but I'm going through a very busy period at work at the moment and I think that will only get worse in the coming weeks.

**Comment by mefistotelis** [comment]
> The only problem is then potentially hosting game assets

Yeah, my approach is we'll just do it. Separate repo for maps/levels, GFX and SFX. If there are complains, we can then take them down (though they killed the franchise already, so no reason they'd additionally want to anger the few remaining fans). Even with all these files it won't be enough to recreate the whole game, so this can't be treated as substitute/piracy. Original files will be marked as copyrighted, all patches we will apply will be under GPL.

For GFX/SFX, the repo will contain separate PNGs/WAVs, convertable to game engine format by a tool.

> I will try and make some kind of basic level editor

Yeah, you'll probably need that to make quality unguided campaign. The game itself won't be able to have internal editor for a long time (if that ever happens at all).

**Comment by mefistotelis** [comment]
There might be an issue with Commands array of old levels, some coords are zeroed out. Not sure if coords for some Commads are at different positions, or just unset because unfinished.

This is especially visible in `-m 3,38`, but I've also seen maps where spiderbots tried to walk into walls, probably due to the same bug. Also, in some maps Unguided do not enter their cars - if there is an issue, that might be another symptom of it.

**Comment by mefistotelis** [comment]
We can consider the pre-alpha support implemented. Any remaining bugs can be solved in separate issues.
