### ISSUE TITLE
Bug: Modifications text does not display on Cryo screen

### ISSUE THREAD

**Issue by Moburma** [swfans/swars#66]
The text for each cybernetic mod in the cryo screen is no longer written to the screen, instead the box is always blank.

Reproduction: research any mod, and choose it to buy from the list in the cryo screen. The first click shows the animation for the body part in the box, but clicking on it again should show the text blurb for the item. Instead the box is always blank. This is the case for all mods and both fast and slow projector modes. 

Tested with latest Win32 artifact executable.

Screenshot:
[<img src="https://i.ibb.co/L8mjrfH/Swars-Cryo-Bug.png">](https://ibb.co/L8mjrfH)

**Comment by mefistotelis** [comment]
Can you bisect that?

Meaning, check older builds to figure out at which point (at which commit) the issue started?

**Comment by Moburma** [comment]
Seems to have broken with this commit: 
[https://github.com/swfans/swars/commit/bff37a7d13969b37490800b63abebb80c5c96846](https://github.com/swfans/swars/commit/bff37a7d13969b37490800b63abebb80c5c96846)
Makes sense as it's rewriting the weapon texts

**Comment by mefistotelis** [comment]
Yep, re-enabling the old `init_weapon_text` makes this issue disappear.

Thank you; will find the mistake in my rewrite.

**Comment by mefistotelis** [comment]
The parser code is so lazy, looking at it makes me feel dirty.

Anyway, fixed.

Soon we will have to make a tool to re-create the text WAD files; then I will change the file format to standard-compliant INI file, and then the parser can be replaced by normal INI parser.
