### ISSUE TITLE
Default per-user options are hard-coded

### ISSUE THREAD

**Issue by mefistotelis** [swfans/swars#68]
> For default options, in one of recent changes I introduced "Anon" as default login name - so if you copy your file to `ANON.INI`, it should load it at startup. (previously there was no default name, so the game tried to load `.INI` file, which was bad).

This doesn't seem to work properly. It loads at startup, so it skips the projector animations at the start (with fast projector) when you're not logged in, but as soon as you make a new user it goes back to the defaults (not from the `ANON.INI`, but actual game defaults like VGA resolution, no keybinds etc.).

_Originally posted by @geist22 in https://github.com/swfans/swars/issues/38#issuecomment-1693446396_

**Comment by mefistotelis** [comment]
Ok, it would make sense to do something more unified here. Idea:

* In clean game install, the default per-user options are hard-coded
* User can create a file `DEFAULT.INI` to override the default options
* Options from `DEFAULT.INI`, if exist, shall be used in main menu
* Options from `DEFAULT.INI`, if exist, shall be used as initial options for new user names
* Options from `DEFAULT.INI`, if exist, shall be used when playing single maps with `-m` command

**Comment by mefistotelis** [comment]
Should now be implemented according to the above spec - please verify.

Also, if you want to use a specific user config file rather than default user, you can use `-u <name>` command line param.
(that was implemented earlier)

**Comment by geist22** [comment]
>     * Options from `DEFAULT.INI`, if exist, shall be used when playing single maps with `-m` command

This does not work for me, game started with -m command still uses default settings. The rest works.

**Comment by mefistotelis** [comment]
Hm...

My scenario:
1. Log in as user Q in new game
2. Change all volume values to 0
3. Save the game (under any slot and any name, we don't care for the save game, only for settings file)
4. Copy `Q.INI` to `default.ini`
5. run `swars.exe -W -q -m 0,88`

Result: the game starts without sound.

So, this seem to work for me (though the game still starts in low resolution mode).

**Comment by geist22** [comment]
Yes. `-m` always starts in VGA mode and with default agent color, but the other stuff from the ini works.

Also, if I change the interface color in the ini, `-m` initially starts with only the map from that, rest default, but changing resolution fixes it.
![Untitled-1](https://github.com/swfans/swars/assets/107389189/e5e33e9c-b22c-4220-b9f8-076653f9fcab)

**Comment by mefistotelis** [comment]
ok, will look into it.

**Comment by mefistotelis** [comment]
Did a change.

Now the properties should work fine, but not resolution.
To start in high res, you need to switch to high res at start (`-H`) and make sure the resolution will not switch back due to playing intro (`-q`).

There are still substantial differences between how the level is initialized from menu and from command line; but it isn't a good time to unify that, as I don't understand every call.

**Comment by geist22** [comment]
Yeah doing it like that works.

About the intro movie, that has never even played for me in the port, I assumed it was broken. Do you need anything special for it, like different folder structure or additional dependencies?

**Comment by mefistotelis** [comment]
No, I don't think so. Just `INTRO/INTRO.SMK`.

**Comment by geist22** [comment]
Ah. `INTRO.SMK` is in the `QDATA` folder by default. Got it working by creating the `INTRO` folder and put a symlink to the original in it.

**Comment by mefistotelis** [comment]
Assuming no further bugs.
