### ISSUE TITLE
Wrong city names

### ISSUE THREAD

**Issue by geist22** [swfans/swars#78]
Using the latest artifacts, the city names are now wrong in some (but not all) missions, both EuroCorp and Church. The wrong names are on the world map, and in case of missions with multiple destinations the part where you select them as well.

Example:
EuroCorp 0 says Detroit instead of London
EuroCorp 1 says Hong Kong instead of Detroit
EuroCorp 3 says Salzburg, Voss and Nuuk instead of Geneva, Matochkin Shar and Vancouver

**Comment by mefistotelis** [comment]
Did you replaced the WAD file with one from `lang` folder?

**Comment by goofyseeker311** [comment]
> Did you replaced the WAD file with one from `lang` folder?

one more reason to auto-overwrite with the english version automatically, less answering these questions.

**Comment by geist22** [comment]
> Did you replaced the WAD file with one from `lang` folder?

No, I just copied the files in my SWARS folders with the same structure. I see you've added this to the installation process, it works now that I've done this.

Though this seems a bit of a weird way to do things. Wouldn't it be better to just reference to these files from an .ini file instead of having to replace files?

**Comment by mefistotelis** [comment]
This file will be replaced by a set of files, assuming I will finish the rework.

**Comment by geist22** [comment]
Alright.
