### ISSUE TITLE
Wrongly marked mission objectives

### ISSUE THREAD

**Issue by geist22** [swfans/swars#87]
So with the new release I'm having some wrongly marked mission objectives now.

Examples:
1. EuroCorp 10, Adelaide: The marked target isn't the scientist, but the zealot in front of his building.
2. Same mission, Cape Town: Marked target is some random civilian.
3. Same mission, Buenos Aires: Zealots everywhere are marked, but the mission doesn't fail if you kill them.

Santiago seems to be working correctly.

I've tested a few missions but only found this one to be bugged. I know issues like this appeared in the past from changing (or not changing) files such as .ini related to cities or missions, and .idx/.wad. According to the new installation instructions, no special replacement is necessary anymore.

So, `conf` has all the .ini files, `language\eng` in the swars directory and otherwise all the original files. ALLTEXT.IDX and .WAD are now back to original (or deleted, didn't seem to matter) from the previous version which replaced them.
I've also tried it by going through the installer, which results in the same issue, so either my file structure is correct or [Moburma](https://github.com/Moburma) did the same mistakes I did.

**Comment by geist22** [comment]
error.log (for Adelaide):

```
bflibrary ver 0.1.2.0 (standard release)
LOG CREATED  @ 07:53:10  18-11-2023

Error: Bflib: LbFileOpen: file does not exist: "data/tex06.dat"
Error: Bflib: LbFileOpen: file does not exist: "conf\miss004.ini"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "maps/map006.b&b"
Warning: SWars: load_level_pc: Local player group equal 0 will cause issues; fix the level
Warning: Bflib: LbScreenReset: screen got reset while locked
```

**Comment by mefistotelis** [comment]
Well this is weird.

When playing via `-m 0,26` the marked objective is fine. But if going through campaign, it's wrong.

**Comment by mefistotelis** [comment]
Should be fixed with:
```
swars: Introduced find_mission_for_city_in_brief() 
```

The issue was that for multi-mission briefs, objectives for first mission were initialized, rather than for selected one.

**Comment by geist22** [comment]
Yes, works now in the missions I've tested.
