### ISSUE TITLE
Church Mission 22: After bank is destroyed, cars explode when driving through certain areas

### ISSUE THREAD

**Issue by geist22** [swfans/swars#94]
An odd bug I've found, it also happens in the original.

There are some locations, most notably near intersections on the middle street between your starting area and the bank, but also one location up the ramp on the far side of the Unguided area, where cars mysteriously lose all health and immediately explode when they drive through.

It only starts happening after the bank is destroyed, I couldn't reproduce it with other buildings.

**Comment by mefistotelis** [comment]
Reproduces when starting with ` -m 1,19`. After first look it doesn't seem like a bug, but a scripted event.
The Unguided bikes are just mysteriously falling, distance from the bank doesn't seem to matter.

**Comment by Moburma** [comment]
Checking the commands, the unguided in bikers are in the group PUNK BIKERS. They each have commands to get in their respective bike and just wander, but they also have an UNTIL statement to check for the player killing any of their group, then they get told to kill the player group (not sure this even makes any difference - they're already set to kill the player on site anyway). They don't have any other commands to self destruct. To me it looks like an actual bug. 

I might try adding some more vehicles with e.g. civilians in and see if they start blowing up too.

**Comment by Moburma** [comment]
I added a yellow taxi to the level. This definitely will blow up in the same way as the other vehicles, so it's not a commands thing. So I wonder if it's a) a just bug, or b) actually some kind of hard coded feature?

File here if you want to try (taxi tends to die fast though!)

https://easyupload.io/q3z4hd

**Comment by mefistotelis** [comment]
Well that's unusual..

The vehicles travel between what is called traffic nodes. If the game finds a broken link in the traffic nodes, it doesn't know how to proceed. To avoid having the vehicle just stop reacting, it then crashes the vehicle.

so.. destroying the bank somehow breaks the link between traffic nodes?

**Comment by mefistotelis** [comment]
Ok I see the problem.

Most vehicles have links to traffic nodes in `p_vehicle->U.UVehicle.TNode`. Except trains. Trains link to stations (= building things) there.

When a station explodes, the train vehicle should go down.

The bug is, the game periodically treats other vehicles as trains and uses `UVehicle.TNode` as Thing reference, when it really is TrafficNode reference. It references a thing, usually building, which just happens to have the same index as TraffcNode.

That would suggest every level has random buildings which the game treats as "stations" for normal vehicles. We've found this one only because it happens to be a bank, and these you often blow up.

**Comment by geist22** [comment]
Haha. I would have thought there was a script on the bank that triggered when it was destroyed, since it was only in this mission and only with the bank. But now that you've found this I went ahead on a building demolishion spree to look for other instances of this happening, and they do indeed exist.

For example, in EuroCorp 10: Adelaide, it's the billboard south of your starting location.

**Comment by mefistotelis** [comment]
I think me rewriting `process_next_tnode()` fixed this.
I hope I didn't created other vehicle pathfinding bugs - this function was quite complex.

**Comment by geist22** [comment]
Looks fixed, vehicles no longer get destoryed on both maps I've tried.

On a side note, could this also have fixed the scientist in EuroCorp mission 5? Looks like it, but it takes him so long to complete his route that it's hard to get a reliable sample size.

**Comment by mefistotelis** [comment]
Yeah, we should introduce frameskip mode, like it is done in DK.

Currently one can only unlock the speed in code. This change should do it:

```
void game_update(void)
{
-    game_update_full(true);
+    game_update_full(false);
}
```

**Comment by geist22** [comment]
Really looks like the scientist is fixed - almost sad we didn't have an issue for him 🙃

Anyway, closing this as mysteriously exploding cars are no longer an issue.
