### ISSUE TITLE
Completed research and scientists dead are misaligned on debriefing screen

### ISSUE THREAD

**Issue by geist22** [swfans/swars#95]
Using the latest version.

![debriefing](https://github.com/swfans/swars/assets/107389189/090f0eb7-4419-494c-b59f-0235738f77a5)

**Comment by mefistotelis** [comment]
Should be fixed with:
https://github.com/swfans/swars/commit/478e249ebb57f870a77c9da61d552a66dec6256f

**Comment by geist22** [comment]
When I research the Minigun with the Church, the debriefing actually tells me that it was Pulse Laser.
On a new campaign completing the missions with cheats.

**Comment by geist22** [comment]
Confirmed.
