### ISSUE TITLE
Church campaign mission order bugs

### ISSUE THREAD

**Issue by geist22** [swfans/swars#96]
I've tested this with the `misXXX.ini` from both the latest source code archive and from the recent release.

When completing Church mission 5 and 6 while leaving mission 4, 7 and 8 will be offered while 4 is still up. Doing some of 7 and 8, 4 will disappear and 9 & 10 will be offered, and they're the same as 7 & 8. After that 11 & 12 will be offered, which are actually 9 and 10.

**Comment by mefistotelis** [comment]
If I understand correctly, the mission progress deviates from this chart:
https://github.com/swfans/swars/blob/master/doc/campaign-church-missions.md

The deviation is that Source=31 and Source=32 can be activated without completing all of: Source=28, Source=29, Source=30.

Relevant part of `mis001.ini`:
```
[mission31]
Name = CH07 HONG KONG - HERETICS
SourceID = 30
SuccessTrigger = 6 11 0
MissionCond = 10 39 17 0 0

[mission17]
Name = CH05 JOHANNESBURG - DONATION
SourceID = 28
SuccessTrigger = 6 11 0
MissionCond = 10 39 31 0 0

[mission39]
Name = CH06C VANCOUVER - SOUL CRUSADER
SourceID = 29
SpecialTrigger = 0 0 10
SuccessTrigger = 6 11 0
MissionCond = 17 10 31 0 0

[mission10]
Name = CH06A GENEVA - LEARNING
SourceID = 29
SpecialTrigger = 0 39 10
SuccessTrigger = 6 11 0
MissionCond = 17 39 31 0 0
```

**Comment by geist22** [comment]
I've checked all the scenarios with multiple missions during the church campaign, it works as intended now, at least in the order I've tested.
